[package]
name = "subvt-validator-list-server"
version = "0.13.17"
edition = "2021"
rust-version = "1.63.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
bus = "2.2.4"
chrono = "0.4"
clap = "4.0"
env_logger = "0.9.0"
futures-util = "0.3.21"
jsonrpsee = { version = "0.15.1", features = ["full"] }
lazy_static = "1.4.0"
log = "0.4.16"
once_cell = "1.13"
redis = { version = "0.22.1", features = ["tokio-comp"] }
rustc-hash = "1.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
subvt-config = { path = "../subvt-config" }
subvt-metrics = { path = "../subvt-metrics" }
subvt-service-common = { path = "../subvt-service-common" }
subvt-types = { path = "../subvt-types" }
subvt-logging = { path = "../subvt-logging" }
tokio = { version = "1.20", features = ["full"] }
