[package]
name = "subvt-plotter"
version = "0.14.15"
edition = "2021"
rust-version = "1.65.0"

[dependencies]
anyhow = "1.0"
chrono = "0.4"
env_logger = "0.10.0"
format_num = "0.1.0"
itertools = "0.10.3"
lazy_static = "1.4.0"
log = "0.4.16"
thiserror = "1.0"
rand = "0.8.5"
resvg = "0.28.0"
rustc-hash = "1.1.0"
subvt-config = { path = "../subvt-config" }
subvt-types = { path = "../subvt-types" }
subvt-utility = { path = "../subvt-utility" }
svg = "0.12.1"
tiny-skia = "0.8.2"
usvg = "0.27.0"