[substrate]
chain = "kusama"
chain_display = "Kusama"
chain_genesis_hash = "0xB0A8D493285C2DF73290DFB7E61F870F17B41801197A149CA93654499EA3DAFE"
epochs_per_era = 6
rpc_url = "wss://rpc.helikon.io/kusama"
people_rpc_url = "wss://rpc.helikon.io/people-kusama"
network_id = 1
token_ticker = "KSM"
token_decimals = 12

[block_processor]
# min supported for Kusama is 4_401_243, metadata v12
# first block of 2021 for Kusama is 6_015_486
start_block_number = 6_015_486

[dn]
data_endpoint = "https://nodes.web3.foundation/api/cohort/1/kusama"

[notification_generator]
unclaimed_payout_check_delay_hours = 3

[session_validator_performance_updater]
start_session_index = 5000