[substrate]
chain = "polkadot"
chain_display = "Polkadot"
chain_genesis_hash = "0x91B171BB158E2D3848FA23A9F1C25182FB8E20313B2C1EB49219DA7A70CE90C3"
epochs_per_era = 6
rpc_url = "wss://rpc.helikon.io/polkadot"
people_rpc_url = "wss://rpc.helikon.io/people-polkadot"
network_id = 2
token_ticker = "DOT"
token_decimals = 10

[block_processor]
# min supported for Polkadot is 2_005_673, metadata v12
# first block of 2021 for Polkadot is 2_700_565
start_block_number = 2_700_565

[dn]
data_endpoint = "https://nodes.web3.foundation/api/cohort/1/polkadot"

[notification_generator]
unclaimed_payout_check_delay_hours = 9