[package]
name = "subvt-service-common"
version = "0.3.3"
edition = "2021"
rust-version = "1.60.0"

[dependencies]
actix-web = "4.0.0"
anyhow = "1.0.57"
async-trait = "0.1.53"
log = "0.4.17"
serde_json = "1.0.79"
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.20" }
subvt-config = { path = "../subvt-config" }
subvt-logging = { path = "../subvt-logging" }
subvt-metrics = { path = "../subvt-metrics" }
subvt-types = { path = "../subvt-types" }
tokio = { version = "1.18.1", features = ["full"] }