[package]
name = "subvt-governance"
version = "0.3.3"
edition = "2021"
rust-version = "1.60.0"

[dependencies]
anyhow = "1.0.57"
lazy_static = "1.4.0"
log = "0.4.17"
reqwest = { version = "0.11.10", features = ["blocking", "json", "gzip", "brotli"] }
serde_json = "1.0.81"
subvt-config = { path = "../subvt-config" }
subvt-types = { path = "../subvt-types" }