[package]
name = "subvt-governance"
version = "0.14.23"
edition = "2021"
rust-version = "1.65.0"

[dependencies]
anyhow = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }
reqwest = { version = "0.11.14", features = ["blocking", "json", "gzip", "brotli"] }
serde_json = "1.0"
subvt-config = { path = "../subvt-config" }
subvt-types = { path = "../subvt-types" }