[package]
name = "subvt-notification-generator"
version = "0.3.3"
edition = "2021"
rust-version = "1.60.0"

[dependencies]
anyhow = "1.0.57"
async-lock = "2.5.0"
async-trait = "0.1.53"
chrono = { version = "0.4.19" }
futures = "0.3.21"
futures-util = "0.3.21"
lazy_static = "1.4.0"
log = "0.4.17"
once_cell = "1.10.0"
redis = "0.21.5"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.79"
subvt-config = { path = "../subvt-config" }
subvt-service-common = { path = "../subvt-service-common" }
subvt-types = { path = "../subvt-types" }
subvt-logging = { path = "../subvt-logging" }
subvt-metrics = { path = "../subvt-metrics" }
subvt-persistence = { path = "../subvt-persistence" }
subvt-substrate-client = { path = "../subvt-substrate-client" }
tokio = { version = "1.18.1", features = ["full"] }