[package]
name = "subvt-notification-generator"
version = "0.13.16"
edition = "2021"
rust-version = "1.63.0"

[dependencies]
anyhow = "1.0"
async-lock = "2.5.0"
async-trait = "0.1"
chrono = "0.4"
futures = "0.3.21"
futures-util = "0.3.21"
lazy_static = "1.4.0"
log = "0.4.16"
once_cell = "1.13"
redis = "0.22.0"
rustc-hash = "1.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
subvt-config = { path = "../subvt-config" }
subvt-service-common = { path = "../subvt-service-common" }
subvt-types = { path = "../subvt-types" }
subvt-logging = { path = "../subvt-logging" }
subvt-metrics = { path = "../subvt-metrics" }
subvt-persistence = { path = "../subvt-persistence" }
subvt-substrate-client = { path = "../subvt-substrate-client" }
tokio = { version = "1.20", features = ["full"] }