[package]
name = "subvt-utility"
version = "0.14.15"
edition = "2021"
rust-version = "1.65.0"

[dependencies]
anyhow = "1.0"
hex = "0.4"
num-format = "0.4.4"
parity-scale-codec = { version = "3.1.5", default-features = false, features = ["derive", "full"] }