[package]
name = "subvt-utility"
version = "0.17.40"
edition = "2021"
rust-version = "1.67.0"

[dependencies]
anyhow = { workspace = true }
hex = "0.4"
num-format = "0.4"
parity-scale-codec = { version = "3.6", default-features = false, features = ["derive", "full"] }