[package]
name = "subvt-utility"
version = "0.1.2"
edition = "2021"
rust-version = "1.56.0"

[dependencies]
anyhow = "1.0.56"
hex = "0.4"
num-format = "0.4.0"
parity-scale-codec = { version = "3.1.0", default-features = false, features = ["derive", "full"] }